// File: src/main/java/org/example/iam/dto/Oauth2ConfigDto.java
package org.example.iam.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.example.iam.entity.Oauth2Config; // For mapping from entity
import org.hibernate.validator.constraints.URL; // For URL validation

import java.time.Instant;
import java.util.UUID;

/**
 * Data Transfer Object (DTO) for representing and updating OAuth 2.0 Client configuration
 * associated with an Organization.
 * <p>
 * Used in API requests and responses for managing OAuth2 SSO settings.
 * Sensitive fields like the client secret are handled carefully:
 * - {@code clientSecretInput} is used for input during updates (write-only).
 * - The actual secret is not included in response DTOs generated by {@code fromEntity}.
 * </p>
 * Includes validation and Swagger annotations.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
//@JsonInclude(JsonInclude.Include.NON_NULL) // Exclude null fields from JSON output
@Schema(description = "Represents the OAuth 2.0 Client configuration settings for an Organization, used for SSO.")
public class Oauth2ConfigDto {

  @Schema(description = "Unique identifier (UUID) of the OAuth2 configuration record itself.",
          accessMode = Schema.AccessMode.READ_ONLY) // Read-only in responses
  private UUID id;

  @Schema(description = "Unique identifier (UUID) of the Organization this configuration belongs to.",
          accessMode = Schema.AccessMode.READ_ONLY) // Read-only in responses
  private UUID organizationId;

  // --- Configuration Fields ---

  @NotBlank(message = "Provider identifier cannot be blank.")
  @Size(max = 50, message = "Provider identifier cannot exceed 50 characters.")
  @Schema(description = "A unique key identifying the OAuth2 provider (e.g., 'google', 'github', 'custom-okta'). Used as the registrationId suffix in Spring Security.",
          requiredMode = Schema.RequiredMode.REQUIRED, example = "google", maxLength = 50)
  private String provider;

  @NotBlank(message = "Client ID cannot be blank.")
  @Size(max = 255, message = "Client ID cannot exceed 255 characters.")
  @Schema(description = "The Client ID obtained from the OAuth2 provider/authorization server.",
          requiredMode = Schema.RequiredMode.REQUIRED, example = "1234567890-abc.apps.googleusercontent.com", maxLength = 255)
  private String clientId;

  // Use a separate field for inputting the secret during updates.
  // It's marked writeOnly so it doesn't appear in response schemas.
  @Schema(description = "The Client Secret obtained from the OAuth2 provider. Provide this only when creating or changing the secret. Leave blank/null if not updating the secret.",
          requiredMode = Schema.RequiredMode.NOT_REQUIRED, writeOnly = true, example = "GOCSPX-...", nullable = true)
  private String clientSecretInput; // Input only field

  @URL(message = "Authorization URI must be a valid URL, if provided.")
  @Size(max = 1024, message = "Authorization URI cannot exceed 1024 characters.")
  @Schema(description = "The Authorization Endpoint URL of the OAuth2 provider. Required for custom providers not auto-configured by Spring Security.",
          example = "https://accounts.google.com/o/oauth2/v2/auth", nullable = true, maxLength = 1024)
  private String authorizationUri;

  @URL(message = "Token URI must be a valid URL, if provided.")
  @Size(max = 1024, message = "Token URI cannot exceed 1024 characters.")
  @Schema(description = "The Token Endpoint URL of the OAuth2 provider. Required for custom providers.",
          example = "https://oauth2.googleapis.com/token", nullable = true, maxLength = 1024)
  private String tokenUri;

  @URL(message = "UserInfo URI must be a valid URL, if provided.")
  @Size(max = 1024, message = "UserInfo URI cannot exceed 1024 characters.")
  @Schema(description = "The UserInfo Endpoint URL of the OAuth2 provider. Required for custom providers or when user info is needed beyond the ID token.",
          example = "https://www.googleapis.com/oauth2/v3/userinfo", nullable = true, maxLength = 1024)
  private String userInfoUri;

  @URL(message = "JWK Set URI must be a valid URL, if provided.")
  @Size(max = 1024, message = "JWK Set URI cannot exceed 1024 characters.")
  @Schema(description = "The JSON Web Key (JWK) Set URI of the OAuth2 provider, used to verify token signatures. Required for custom providers.",
          example = "https://www.googleapis.com/oauth2/v3/certs", nullable = true, maxLength = 1024)
  private String jwkSetUri;

  // Typically auto-resolved by Spring Security ({baseUrl}/login/oauth2/code/{registrationId}), but can be overridden.
  @Size(max = 1024, message = "Redirect URI Template cannot exceed 1024 characters.")
  @Schema(description = "The callback URL (Redirect URI) pattern registered with the provider where the authorization code is sent. Spring Security often uses '{baseUrl}/login/oauth2/code/{registrationId}'.",
          example = "{baseUrl}/login/oauth2/code/google", nullable = true, maxLength = 1024)
  private String redirectUriTemplate;

  @Size(max = 512, message = "Scopes cannot exceed 512 characters.")
  @Schema(description = "Comma-separated list of OAuth2 scopes to request from the provider (e.g., 'openid,profile,email'). Determines the information accessible.",
          example = "openid,profile,email", nullable = true, maxLength = 512)
  private String scopes; // e.g., "openid,profile,email"

  @Size(max = 100, message = "Username attribute name cannot exceed 100 characters.")
  @Schema(description = "The attribute name within the UserInfo response or ID token that should be used as the primary identifier (principal name) for the authenticated user. Defaults to 'sub' for OIDC.",
          example = "email", nullable = true, maxLength = 100)
  private String userNameAttributeName; // e.g., "sub", "email", "preferred_username", "upn"

  @Size(max = 100, message = "Email attribute name cannot exceed 100 characters.")
  @Schema(description = "The attribute name within the UserInfo response or ID token that contains the user's primary email address. Defaults to 'email'.",
          example = "email", nullable = true, maxLength = 100)
  private String userEmailAttributeName; // e.g., "email"

  @NotNull(message = "Enabled flag must be provided.")
  @Schema(description = "Whether OAuth2 login via this provider is enabled for the organization.",
          requiredMode = Schema.RequiredMode.REQUIRED, example = "true")
  private Boolean enabled;

  // --- Audit Fields (Read-Only) ---
  @Schema(description = "Timestamp when this configuration was created (ISO 8601 format in UTC).",
          accessMode = Schema.AccessMode.READ_ONLY)
  private Instant createdDate;

  @Schema(description = "Timestamp when this configuration was last modified (ISO 8601 format in UTC).",
          accessMode = Schema.AccessMode.READ_ONLY)
  private Instant lastModifiedDate;

  @Schema(description = "Identifier of the user or system that created this configuration.",
          accessMode = Schema.AccessMode.READ_ONLY)
  private String createdBy;

  @Schema(description = "Identifier of the user or system that last modified this configuration.",
          accessMode = Schema.AccessMode.READ_ONLY)
  private String lastModifiedBy;

  /**
   * Static factory method to create an Oauth2ConfigDto from an Oauth2Config entity.
   * This method specifically excludes the sensitive {@code clientSecret} field from the resulting DTO.
   * Handles null input gracefully.
   *
   * @param entity The {@link Oauth2Config} entity.
   * @return A corresponding {@link Oauth2ConfigDto} (without clientSecret), or null if the input entity is null.
   */
  public static Oauth2ConfigDto fromEntity(Oauth2Config entity) {
    if (entity == null) {
      return null;
    }
    return Oauth2ConfigDto.builder()
            .id(entity.getId())
            .organizationId(entity.getOrganization() != null ? entity.getOrganization().getId() : null)
            .provider(entity.getProvider())
            .clientId(entity.getClientId())
            // DO NOT MAP clientSecret to the DTO for responses
            // .clientSecretInput(null) // Input field is not relevant for response
            .authorizationUri(entity.getAuthorizationUri())
            .tokenUri(entity.getTokenUri())
            .userInfoUri(entity.getUserInfoUri())
            .jwkSetUri(entity.getJwkSetUri())
            .redirectUriTemplate(entity.getRedirectUriTemplate())
            .scopes(entity.getScopes())
            .userNameAttributeName(entity.getUserNameAttributeName())
            .userEmailAttributeName(entity.getUserEmailAttributeName())
            .enabled(entity.isEnabled())
            // Audit fields
            .createdDate(entity.getCreatedDate())
            .lastModifiedDate(entity.getLastModifiedDate())
            .createdBy(entity.getCreatedBy())
            .lastModifiedBy(entity.getLastModifiedBy())
            .build();
  }
}