// File: src/main/java/org/example/iam/dto/SamlConfigDto.java
package org.example.iam.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.example.iam.entity.SamlConfig; // For mapping from entity
import org.hibernate.validator.constraints.URL; // For URL validation

import java.time.Instant;
import java.util.UUID;

/**
 * Data Transfer Object (DTO) for representing and updating SAML 2.0 Service Provider (SP)
 * configuration associated with an Organization.
 * <p>
 * Used in API requests and responses for managing SAML SSO settings.
 * Sensitive fields like keystore paths, passwords, and certificates are handled carefully:
 * - They are generally excluded from response DTOs generated by {@code fromEntity}.
 * - Input DTOs accept them, marked as writeOnly in Swagger. Passwords should be plaintext here, service encrypts.
 * - The service layer is responsible for secure handling and storage (encryption, path validation).
 * </p>
 * Includes validation and Swagger annotations.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
//@JsonInclude(JsonInclude.Include.NON_NULL) // Exclude null fields from JSON output
@Schema(description = "Represents the SAML 2.0 Service Provider configuration settings for an Organization, used for SSO.")
public class SamlConfigDto {

  @Schema(description = "Unique identifier (UUID) of the SAML configuration record itself.",
          accessMode = Schema.AccessMode.READ_ONLY)
  private UUID id;

  @Schema(description = "Unique identifier (UUID) of the Organization this configuration belongs to.",
          accessMode = Schema.AccessMode.READ_ONLY)
  private UUID organizationId;

  // --- Configuration Fields ---

  @URL(message = "Identity Provider metadata URL must be a valid URL.")
  @Size(max = 1024, message = "Metadata URL cannot exceed 1024 characters.")
  @Schema(description = "URL from which the Identity Provider's (IdP) metadata XML can be fetched dynamically. If provided, details like IdP entity ID, SSO/SLO URLs, and signing certificates are often derived from this.",
          example = "https://idp.example.com/saml/metadata", nullable = true, maxLength = 1024)
  private String identityProviderMetadataUrl; // Recommended way to configure IdP details

  @NotBlank(message = "Service Provider Entity ID cannot be blank.")
  @Size(max = 255, message = "SP Entity ID cannot exceed 255 characters.")
  @Schema(description = "The unique identifier (Entity ID) for this application (Service Provider) as registered with the IdP for this specific organization.",
          requiredMode = Schema.RequiredMode.REQUIRED, example = "urn:example:iam:sp:org123", maxLength = 255)
  private String serviceProviderEntityId; // Our identifier for this org

  @NotBlank(message = "Assertion Consumer Service (ACS) URL cannot be blank.")
  @URL(message = "ACS URL must be a valid URL.")
  @Size(max = 1024, message = "ACS URL cannot exceed 1024 characters.")
  @Schema(description = "The URL endpoint within this application where the IdP should send the SAML assertion (the callback URL after successful IdP authentication). Typically includes the registration ID.",
          requiredMode = Schema.RequiredMode.REQUIRED, example = "https://myapp.com/login/saml2/sso/saml-org-a1b2c3d4", maxLength = 1024)
  private String assertionConsumerServiceUrl; // Our callback URL

  @URL(message = "Single Logout (SLO) Service URL must be a valid URL, if provided.")
  @Size(max = 1024, message = "SLO URL cannot exceed 1024 characters.")
  @Schema(description = "The URL endpoint within this application where the IdP should send SAML Logout Requests or Responses (optional, required for IdP-initiated logout).",
          example = "https://myapp.com/logout/saml2/slo/saml-org-a1b2c3d4", nullable = true, maxLength = 1024)
  private String singleLogoutServiceUrl; // Our SLO endpoint (optional)

  @Size(max = 100, message = "NameID Format cannot exceed 100 characters.")
  @Schema(description = "The format of the NameID that this SP prefers or requires from the IdP (e.g., email address, persistent, transient).",
          example = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress", nullable = true, maxLength = 100)
  private String nameIdFormat; // e.g., "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"

  @NotNull(message = "Sign Requests flag must be provided.")
  @Schema(description = "Whether SAML AuthnRequests sent from this SP to the IdP should be digitally signed using the SP's private key.",
          requiredMode = Schema.RequiredMode.REQUIRED, example = "false")
  private Boolean signRequests; // Should we sign requests sent to IdP?

  @NotNull(message = "Want Assertions Signed flag must be provided.")
  @Schema(description = "Whether SAML Assertions received from the IdP must be digitally signed. Strongly recommended for security.",
          requiredMode = Schema.RequiredMode.REQUIRED, example = "true")
  private Boolean wantAssertionsSigned; // Do we require assertions from IdP to be signed?

  // --- Certificates/Keys (PKCS12 Keystore based) ---
  // These are inputs for updating the configuration. Marked writeOnly for Swagger.
  // Service layer handles secure storage based on these inputs.
  @Size(max = 255, message = "SP Signing Keystore Path cannot exceed 255 characters.")
  @Schema(description = "Path to the PKCS#12 keystore file containing the SP's signing private key and certificate. Input only.",
          example = "file:/etc/saml/keystores/sp-signing.p12", writeOnly = true, nullable = true)
  private String spSigningKeystorePathInput;

  @Schema(description = "Password for the SP Signing Keystore file and/or the private key entry within it. Input only. Will be encrypted before storage.",
          example = "KeystoreSecurePassword123!", writeOnly = true, nullable = true, format="password")
  private String spSigningKeystorePasswordInput; // Plaintext password input

  @Size(max = 100, message = "SP Signing Key Alias cannot exceed 100 characters.")
  @Schema(description = "The alias identifying the signing key entry within the SP Signing Keystore. Input only.",
          example = "sp-signing-alias", writeOnly = true, nullable = true)
  private String spSigningKeyAliasInput;

  @Size(max = 255, message = "SP Encryption Keystore Path cannot exceed 255 characters.")
  @Schema(description = "Path to the PKCS#12 keystore file containing the SP's encryption/decryption private key and certificate. Input only.",
          example = "file:/etc/saml/keystores/sp-encryption.p12", writeOnly = true, nullable = true)
  private String spEncryptionKeystorePathInput;

  @Schema(description = "Password for the SP Encryption Keystore file and/or the private key entry within it. Input only. Will be encrypted before storage.",
          example = "KeystoreSecurePassword456!", writeOnly = true, nullable = true, format="password")
  private String spEncryptionKeystorePasswordInput; // Plaintext password input

  @Size(max = 100, message = "SP Encryption Key Alias cannot exceed 100 characters.")
  @Schema(description = "The alias identifying the encryption key entry within the SP Encryption Keystore. Input only.",
          example = "sp-encryption-alias", writeOnly = true, nullable = true)
  private String spEncryptionKeyAliasInput;

  @Schema(description = "Identity Provider's public certificate for verifying assertion signatures (PEM format). Input only. Usually obtained from metadata, provide only if overriding or metadata URL is not used.",
          writeOnly = true, nullable = true)
  private String idpVerificationCertificatePemInput; // Input as PEM String


  // --- Attribute Mapping ---
  @Size(max = 100, message = "Username attribute mapping cannot exceed 100 characters.")
  @Schema(description = "Name of the SAML attribute in the assertion to map to the internal user's username/primary identifier. Defaults to 'uid'. Can be overridden.",
          example = "uid", nullable = true, maxLength = 100)
  private String attributeMappingUsername; // e.g., "uid", "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"

  @Size(max = 100, message = "Email attribute mapping cannot exceed 100 characters.")
  @Schema(description = "Name of the SAML attribute in the assertion containing the user's primary email address. Defaults to 'mail'. Can be overridden.",
          example = "mail", nullable = true, maxLength = 100)
  private String attributeMappingEmail; // e.g., "mail", "emailAddress"

  @Size(max = 100, message = "Roles attribute mapping cannot exceed 100 characters.")
  @Schema(description = "Name of the SAML attribute (potentially multi-valued) containing the user's roles/groups. Optional.",
          example = "memberOf", nullable = true, maxLength = 100)
  private String attributeMappingRoles; // e.g., "memberOf", "groups"

  // --- Status ---
  @NotNull(message = "Enabled flag must be provided.")
  @Schema(description = "Whether SAML login is enabled for this organization using this configuration.",
          requiredMode = Schema.RequiredMode.REQUIRED, example = "true")
  private Boolean enabled;

  // --- Audit Fields (Read-Only) ---
  @Schema(description = "Timestamp when this configuration was created (ISO 8601 format in UTC).",
          accessMode = Schema.AccessMode.READ_ONLY)
  private Instant createdDate;

  @Schema(description = "Timestamp when this configuration was last modified (ISO 8601 format in UTC).",
          accessMode = Schema.AccessMode.READ_ONLY)
  private Instant lastModifiedDate;

  @Schema(description = "Identifier of the user or system that created this configuration.",
          accessMode = Schema.AccessMode.READ_ONLY)
  private String createdBy;

  @Schema(description = "Identifier of the user or system that last modified this configuration.",
          accessMode = Schema.AccessMode.READ_ONLY)
  private String lastModifiedBy;


  /**
   * Static factory method to create a SamlConfigDto from a SamlConfig entity.
   * This method specifically excludes potentially sensitive fields like stored
   * certificates or private key references from the resulting DTO.
   * Handles null input gracefully.
   *
   * @param entity The {@link SamlConfig} entity.
   * @return A corresponding {@link SamlConfigDto} (without sensitive fields), or null if the input entity is null.
   */
  public static SamlConfigDto fromEntity(SamlConfig entity) {
    if (entity == null) {
      return null;
    }
    return SamlConfigDto.builder()
            .id(entity.getId())
            .organizationId(entity.getOrganization() != null ? entity.getOrganization().getId() : null)
            .identityProviderMetadataUrl(entity.getIdentityProviderMetadataUrl())
            .serviceProviderEntityId(entity.getServiceProviderEntityId())
            .assertionConsumerServiceUrl(entity.getAssertionConsumerServiceUrl())
            .singleLogoutServiceUrl(entity.getSingleLogoutServiceUrl())
            .nameIdFormat(entity.getNameIdFormat())
            .signRequests(entity.isSignRequests()) // Use boolean getter
            .wantAssertionsSigned(entity.isWantAssertionsSigned()) // Use boolean getter
            // Exclude keystore paths, passwords, aliases, and explicit certs from response DTOs
            .attributeMappingUsername(entity.getAttributeMappingUsername())
            .attributeMappingEmail(entity.getAttributeMappingEmail())
            .attributeMappingRoles(entity.getAttributeMappingRoles())
            .enabled(entity.isEnabled()) // Use boolean getter
            // Audit fields
            .createdDate(entity.getCreatedDate())
            .lastModifiedDate(entity.getLastModifiedDate())
            .createdBy(entity.getCreatedBy())
            .lastModifiedBy(entity.getLastModifiedBy())
            .build();
  }
}