// File: src/main/java/org/example/iam/dto/AuditEventDto.java
package org.example.iam.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.example.iam.constant.AuditEventType; // Although type is String, good to know origin
import org.example.iam.entity.AuditEvent;

import java.time.Instant;
import java.util.UUID;

/**
 * Data Transfer Object (DTO) representing an audit event.
 * Used for transferring audit event information, for example, when publishing events to Kafka
 * or potentially retrieving audit logs via an API (if implemented).
 * <p>
 * Fields mirror the {@link AuditEvent} entity but are decoupled for API/messaging contracts.
 * Includes Lombok annotations for boilerplate code generation and Jackson/Swagger annotations
 * for serialization and documentation.
 * </p>
 */
@Data // Generates getters, setters, toString, equals, hashCode, required args constructor
@Builder // Enables the builder pattern for object creation
@NoArgsConstructor // Generates a no-arguments constructor (needed by Jackson/JPA)
@AllArgsConstructor // Generates an all-arguments constructor
@JsonInclude(JsonInclude.Include.NON_NULL) // Exclude null fields during JSON serialization
@Schema(description = "Represents a single audit event record detailing an action or system event")
public class AuditEventDto {

  @Schema(description = "Unique identifier for this specific event instance",
          example = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          accessMode = Schema.AccessMode.READ_ONLY) // Usually generated server-side
  private UUID eventId;

  @Schema(description = "Timestamp when the event occurred (ISO 8601 format in UTC)",
          example = "2025-04-14T15:30:05.123Z",
          accessMode = Schema.AccessMode.READ_ONLY) // Usually generated server-side
  private Instant eventTimestamp;

  @Schema(description = "Type of the event, corresponding to AuditEventType enum names",
          example = "USER_CREATED")
  private String eventType; // String representation of AuditEventType

  @Schema(description = "Identifier of the user or system that performed the action",
          example = "adminuser@example.com or SYSTEM")
  private String actor;

  @Schema(description = "Outcome status of the event", example = "SUCCESS / FAILURE")
  private String status;

  @Schema(description = "A human-readable description of the event",
          example = "User 'newuser' created by adminuser@example.com")
  private String description;

  @Schema(description = "Type of the primary resource affected by the event (e.g., USER, ORGANIZATION, SAML_CONFIG)",
          nullable = true, example = "USER")
  private String targetResourceType;

  @Schema(description = "Identifier (usually UUID) of the primary resource affected",
          nullable = true, example = "f0e9d8c7-b6a5-4321-fedc-ba9876543210")
  private String targetResourceId; // Use String to accommodate different ID types if needed

  @Schema(description = "Identifier (UUID) of the organization context in which the event occurred",
          nullable = true, example = "a1b2c3d4-e5f6-7890-abcd-ef1234567890")
  private UUID organizationId; // UUID for org context

  @Schema(description = "Additional contextual details about the event, often stored as a JSON string or descriptive text",
          nullable = true, example = "{\"oldValue\": \"xxx\", \"newValue\": \"yyy\"} or Failed due to timeout")
  private String details; // Can store JSON details or simple text

  /**
   * Static factory method to create an AuditEventDto from an AuditEvent entity.
   * Handles null input gracefully.
   *
   * @param entity The {@link AuditEvent} entity.
   * @return A corresponding {@link AuditEventDto}, or null if the input entity is null.
   */
  public static AuditEventDto fromEntity(AuditEvent entity) {
    if (entity == null) {
      return null;
    }
    // Uses the builder pattern generated by Lombok's @Builder
    return AuditEventDto.builder()
            .eventId(entity.getEventId())
            .eventTimestamp(entity.getEventTimestamp())
            .eventType(entity.getEventType()) // Assumes entity stores string name
            .actor(entity.getActor())
            .status(entity.getStatus())
            .description(entity.getDescription())
            .targetResourceType(entity.getTargetResourceType())
            .targetResourceId(entity.getTargetResourceId())
            .organizationId(entity.getOrganizationId())
            .details(entity.getDetails())
            .build();
  }
}