// File: src/main/java/org/example/iam/dto/SamlConfigDto.java
package org.example.iam.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.example.iam.entity.SamlConfig; // For mapping from entity
import org.hibernate.validator.constraints.URL; // For URL validation
import org.springframework.security.saml2.provider.service.registration.Saml2MessageBinding; // For binding enum

import java.time.Instant;
import java.util.UUID;

/**
 * Data Transfer Object (DTO) for representing and updating SAML 2.0 Service Provider (SP)
 * configuration associated with an Organization.
 * <p>
 * Used in API requests and responses for managing SAML SSO settings.
 * Sensitive fields like keystore paths, passwords (keystore and key alias), and certificates are handled carefully:
 * - They are generally excluded from response DTOs generated by {@code fromEntity}.
 * - Input DTOs accept them, marked with {@code accessMode = WRITE_ONLY} in Swagger. Passwords should be plaintext here; the service layer encrypts them.
 * - The service layer is responsible for secure handling and storage (encryption, path validation).
 * </p>
 * Includes validation and Swagger annotations.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
//@JsonInclude(JsonInclude.Include.NON_NULL) // Keep commented unless explicitly needed
@Schema(description = "Represents the SAML 2.0 Service Provider configuration settings for an Organization, used for SSO.")
public class SamlConfigDto {

  @Schema(description = "Unique identifier (UUID) of the SAML configuration record itself.",
          accessMode = Schema.AccessMode.READ_ONLY) // Read-only in responses
  private UUID id;

  @Schema(description = "Unique identifier (UUID) of the Organization this configuration belongs to.",
          accessMode = Schema.AccessMode.READ_ONLY) // Read-only in responses
  private UUID organizationId;

  // --- Configuration Fields ---

  @URL(message = "Identity Provider metadata URL must be a valid URL.")
  @Size(max = 1024, message = "Metadata URL cannot exceed 1024 characters.")
  @Schema(description = "URL from which the Identity Provider's (IdP) metadata XML can be fetched dynamically. If provided, details like IdP entity ID, SSO/SLO URLs, and signing certificates are often derived from this.",
          example = "https://idp.example.com/saml/metadata", nullable = true, maxLength = 1024)
  private String identityProviderMetadataUrl; // Recommended way to configure IdP details

  @NotBlank(message = "Service Provider Entity ID cannot be blank.")
  @Size(max = 255, message = "SP Entity ID cannot exceed 255 characters.")
  @Schema(description = "The unique identifier (Entity ID) for this application (Service Provider) as registered with the IdP for this specific organization.",
          requiredMode = Schema.RequiredMode.REQUIRED, example = "urn:example:iam:sp:org123", maxLength = 255)
  private String serviceProviderEntityId; // Our identifier for this org

  @NotBlank(message = "Assertion Consumer Service (ACS) URL cannot be blank.")
  @URL(message = "ACS URL must be a valid URL.")
  @Size(max = 1024, message = "ACS URL cannot exceed 1024 characters.")
  @Schema(description = "The URL endpoint within this application where the IdP should send the SAML assertion (the callback URL after successful IdP authentication). Typically includes the registration ID.",
          requiredMode = Schema.RequiredMode.REQUIRED, example = "https://myapp.com/login/saml2/sso/saml-org-a1b2c3d4", maxLength = 1024)
  private String assertionConsumerServiceUrl; // Our callback URL

  @URL(message = "Single Logout (SLO) Service URL must be a valid URL, if provided.")
  @Size(max = 1024, message = "SLO URL cannot exceed 1024 characters.")
  @Schema(description = "The URL endpoint within this application where the IdP should send SAML Logout Requests or Responses (optional, required for IdP-initiated logout).",
          example = "https://myapp.com/logout/saml2/slo/saml-org-a1b2c3d4", nullable = true, maxLength = 1024)
  private String singleLogoutServiceUrl; // Our SLO endpoint (optional)

  @Size(max = 100, message = "NameID Format cannot exceed 100 characters.")
  @Schema(description = "The format of the NameID that this SP prefers or requires from the IdP (e.g., email address, persistent, transient).",
          example = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress", nullable = true, maxLength = 100)
  private String nameIdFormat; // e.g., "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"

  @NotNull(message = "Sign Requests flag must be provided.")
  @Schema(description = "Whether SAML AuthnRequests sent from this SP to the IdP should be digitally signed using the SP's signing private key.",
          requiredMode = Schema.RequiredMode.REQUIRED, example = "false")
  private Boolean signRequests; // Should we sign requests sent to IdP?

  @NotNull(message = "Want Assertions Signed flag must be provided.")
  @Schema(description = "Whether SAML Assertions received from the IdP must be digitally signed. Strongly recommended for security.",
          requiredMode = Schema.RequiredMode.REQUIRED, example = "true")
  private Boolean wantAssertionsSigned; // Do we require assertions from IdP to be signed?


  // --- Manual IdP Configuration Fields (Fallback) ---
  @Size(max = 255, message = "IdP Entity ID cannot exceed 255 characters.")
  @Schema(description = "Manual configuration for IdP Entity ID. Used only if Metadata URL is missing or fails to load.",
          example = "http://www.okta.com/exkabcdefg123", nullable = true, maxLength = 255)
  private String identityProviderEntityId; // Optional input

  @URL(message = "IdP Single Sign-On URL must be a valid URL, if provided for manual config.")
  @Size(max = 1024, message = "IdP SSO URL cannot exceed 1024 characters.")
  @Schema(description = "Manual configuration for the IdP's Single Sign-On service URL. Used only if Metadata URL is missing or fails.",
          example = "https://your-org.okta.com/app/your-app/exkabcdefg123/sso/saml", nullable = true, maxLength = 1024)
  private String singleSignOnServiceUrl; // Optional input

  @Schema(description = "Manual configuration for the SAML binding the IdP uses for SSO (e.g., POST, REDIRECT). Used only if Metadata URL is missing or fails.",
          example = "POST", nullable = true, implementation = Saml2MessageBinding.class)
  private Saml2MessageBinding singleSignOnServiceBinding; // Optional input


  // --- Credentials (Inputs Only - Marked WRITE_ONLY) ---
  @Size(max = 255, message = "SP Signing Keystore Path cannot exceed 255 characters.")
  @Schema(description = "Path to the PKCS#12 keystore file containing the SP's signing private key and certificate. Input only.",
          example = "file:/etc/saml/keystores/sp-signing.p12",
          accessMode = Schema.AccessMode.WRITE_ONLY, // Use accessMode instead of writeOnly
          nullable = true)
  private String spSigningKeystorePathInput;

  @Schema(description = "Password for the SP Signing Keystore file. Input only. Will be encrypted before storage.",
          example = "KeystoreSecurePassword123!",
          accessMode = Schema.AccessMode.WRITE_ONLY,
          nullable = true, format="password")
  private String spSigningKeystorePasswordInput; // Plaintext password input

  @Size(max = 100, message = "SP Signing Key Alias cannot exceed 100 characters.")
  @Schema(description = "The alias identifying the signing key entry within the SP Signing Keystore. Input only.",
          example = "sp-signing-alias",
          accessMode = Schema.AccessMode.WRITE_ONLY,
          nullable = true)
  private String spSigningKeyAliasInput;

  @Schema(description = "Password ONLY for the SP Signing private key alias within the keystore. Input only. Will be encrypted. Leave blank/null if same as keystore password.",
          example = "PrivateKeyAliasPassword!",
          accessMode = Schema.AccessMode.WRITE_ONLY, // Use accessMode
          nullable = true, format="password")
  private String spSigningKeyPasswordInput; // Plaintext key alias password input

  @Size(max = 255, message = "SP Encryption Keystore Path cannot exceed 255 characters.")
  @Schema(description = "Path to the PKCS#12 keystore file containing the SP's encryption/decryption private key and certificate. Input only.",
          example = "file:/etc/saml/keystores/sp-encryption.p12",
          accessMode = Schema.AccessMode.WRITE_ONLY,
          nullable = true)
  private String spEncryptionKeystorePathInput;

  @Schema(description = "Password for the SP Encryption Keystore file. Input only. Will be encrypted before storage.",
          example = "KeystoreSecurePassword456!",
          accessMode = Schema.AccessMode.WRITE_ONLY,
          nullable = true, format="password")
  private String spEncryptionKeystorePasswordInput; // Plaintext password input

  @Size(max = 100, message = "SP Encryption Key Alias cannot exceed 100 characters.")
  @Schema(description = "The alias identifying the encryption key entry within the SP Encryption Keystore. Input only.",
          example = "sp-encryption-alias",
          accessMode = Schema.AccessMode.WRITE_ONLY,
          nullable = true)
  private String spEncryptionKeyAliasInput;

  @Schema(description = "Password ONLY for the SP Encryption private key alias within the keystore. Input only. Will be encrypted. Leave blank/null if same as keystore password.",
          example = "PrivateKeyAliasPassword789!",
          accessMode = Schema.AccessMode.WRITE_ONLY, // Use accessMode
          nullable = true, format="password")
  private String spEncryptionKeyPasswordInput; // Plaintext key alias password input

  @Schema(description = "Identity Provider's public certificate for verifying assertion signatures (PEM format). Input only. Provide only if overriding or metadata URL is not used.",
          accessMode = Schema.AccessMode.WRITE_ONLY,
          nullable = true)
  private String idpVerificationCertificatePemInput; // Input as PEM String


  // --- Attribute Mapping ---
  @Size(max = 100, message = "Username attribute mapping cannot exceed 100 characters.")
  @Schema(description = "Name of the SAML attribute in the assertion to map to the internal user's username/primary identifier. Defaults to 'uid'.",
          example = "uid", nullable = true, maxLength = 100)
  private String attributeMappingUsername;

  @Size(max = 100, message = "Email attribute mapping cannot exceed 100 characters.")
  @Schema(description = "Name of the SAML attribute in the assertion containing the user's primary email address. Defaults to 'mail'.",
          example = "mail", nullable = true, maxLength = 100)
  private String attributeMappingEmail;

  @Size(max = 100, message = "Roles attribute mapping cannot exceed 100 characters.")
  @Schema(description = "Name of the SAML attribute (potentially multi-valued) containing the user's roles/groups. Optional.",
          example = "memberOf", nullable = true, maxLength = 100)
  private String attributeMappingRoles;

  // --- Status ---
  @NotNull(message = "Enabled flag must be provided.")
  @Schema(description = "Whether SAML login is enabled for this organization using this configuration.",
          requiredMode = Schema.RequiredMode.REQUIRED, example = "true")
  private Boolean enabled;

  // --- Audit Fields (Read-Only) ---
  @Schema(description = "Timestamp when this configuration was created.", accessMode = Schema.AccessMode.READ_ONLY)
  private Instant createdDate;
  @Schema(description = "Timestamp when this configuration was last modified.", accessMode = Schema.AccessMode.READ_ONLY)
  private Instant lastModifiedDate;
  @Schema(description = "Creator identifier.", accessMode = Schema.AccessMode.READ_ONLY)
  private String createdBy;
  @Schema(description = "Last modifier identifier.", accessMode = Schema.AccessMode.READ_ONLY)
  private String lastModifiedBy;


  /**
   * Static factory method to create a SamlConfigDto from a SamlConfig entity.
   * Excludes sensitive fields like passwords and explicit certificates.
   */
  public static SamlConfigDto fromEntity(SamlConfig entity) {
    if (entity == null) return null;
    return SamlConfigDto.builder()
            .id(entity.getId())
            .organizationId(entity.getOrganization() != null ? entity.getOrganization().getId() : null)
            .identityProviderMetadataUrl(entity.getIdentityProviderMetadataUrl())
            .serviceProviderEntityId(entity.getServiceProviderEntityId())
            .assertionConsumerServiceUrl(entity.getAssertionConsumerServiceUrl())
            .singleLogoutServiceUrl(entity.getSingleLogoutServiceUrl())
            .nameIdFormat(entity.getNameIdFormat())
            .signRequests(entity.isSignRequests())
            .wantAssertionsSigned(entity.isWantAssertionsSigned())
            .attributeMappingUsername(entity.getAttributeMappingUsername())
            .attributeMappingEmail(entity.getAttributeMappingEmail())
            .attributeMappingRoles(entity.getAttributeMappingRoles())
            .identityProviderEntityId(entity.getIdentityProviderEntityId())
            .singleSignOnServiceUrl(entity.getSingleSignOnServiceUrl())
            .singleSignOnServiceBinding(entity.getSingleSignOnServiceBinding())
            .enabled(entity.isEnabled())
            .createdDate(entity.getCreatedDate())
            .lastModifiedDate(entity.getLastModifiedDate())
            .createdBy(entity.getCreatedBy())
            .lastModifiedBy(entity.getLastModifiedBy())
            // Exclude all ...Input fields from response DTO
            .build();
  }
}